updating final exam tasks
victoriadim/Programming_with_Python pull request #3
Opened 2023-11-23 15:42 UTC by victoriadim

2023-11-27 16:51 UTC, nsveli requested changes

2023-11-27 16:51 UTC, nsveli commented on Programming Fundamentals/Final Exam Preparation/Ad Astra.py
> +pattern = re.compile(r"([#|])(?P<item>[A-Za-z\s]+)\1(?P<expiration_date>[0-9]{2}/[0-9]{2}/[0-9]{2})\1(?P<calories>[0-9]+)\1")
този регекс пробвай да го промениш малко спрямо този, който бяхме направили заедно

2023-11-27 16:51 UTC, nsveli commented on Programming Fundamentals/Final Exam Preparation/Fancy Barcodes.py
> +    pattern = r'@#+[A-Z][A-Za-z0-9]{4,}[A-Z]@#+'
този регекс как би си го обяснила?

2023-11-27 16:51 UTC, nsveli commented on Programming Fundamentals/Final Exam Preparation/The Imitation Game.py
> +def decode_message(message, commands):
за бъдещите ПР-и (pull requests) ще е хубаво в началото на питонския код да добавяш в тройни кавички условието на задачата. Може да разгледая [този туториъл](https://flexiple.com/python/block-comment-python)

2023-11-29 19:03 UTC, victoriadim commented on Programming Fundamentals/Final Exam Preparation/Need for Speed III.py
> +        if command == 'Stop':
1. ще продължава да приема команди
2. отново ще приеме командата но output-a ще е грешен

2023-11-29 19:04 UTC, victoriadim commented on Programming Fundamentals/Final Exam Preparation/The Imitation Game.py
> +def decode_message(message, commands):
В следващите задачи вече има сложено условие.

2023-11-30 15:39 UTC, nsveli commented on Programming Fundamentals/Final Exam Preparation/Need for Speed III.py
> +        if command == 'Stop':
For Homework

2023-11-30 15:40 UTC, merged